### ISSUE TITLE
no wok

### ISSUE THREAD

**Issue by CreeperPlays689** [Icesito68/Hp-255-G8-Ryzentosh#1]

**Comment by Icesito68** [comment]
Can you give details of the team you are trying it on?
in addition to the part of the installation process you are in

**Comment by palladinoandrea** [comment]
hi, I have the 5700u version of your PC, it works for me (I only have my own ACPI folder while I copied the settings from yours) and it's just that when I reach a certain point, the PC freezes, doesn't respond to the keyboard or to the touchpad, why?
